//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 06:22:33 PM IST 
//


package com.bitwiseglobal.graph.filter;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bitwiseglobal.graph.filter package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bitwiseglobal.graph.filter
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TypeFilterOperationInputFields }
     * 
     */
    public TypeFilterOperationInputFields createTypeFilterOperationInputFields() {
        return new TypeFilterOperationInputFields();
    }

    /**
     * Create an instance of {@link TypeFilterOperationInputField }
     * 
     */
    public TypeFilterOperationInputField createTypeFilterOperationInputField() {
        return new TypeFilterOperationInputField();
    }

    /**
     * Create an instance of {@link TypeOutSocketAsInSocketIn0 }
     * 
     */
    public TypeOutSocketAsInSocketIn0 createTypeOutSocketAsInSocketIn0() {
        return new TypeOutSocketAsInSocketIn0();
    }

    /**
     * Create an instance of {@link TypeFilterOutSocket }
     * 
     */
    public TypeFilterOutSocket createTypeFilterOutSocket() {
        return new TypeFilterOutSocket();
    }

    /**
     * Create an instance of {@link TypeFilterOperation }
     * 
     */
    public TypeFilterOperation createTypeFilterOperation() {
        return new TypeFilterOperation();
    }

    /**
     * Create an instance of {@link TypeFilterInSocket }
     * 
     */
    public TypeFilterInSocket createTypeFilterInSocket() {
        return new TypeFilterInSocket();
    }

}
