//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.28 at 02:50:05 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bitwiseglobal.com/graph/filter")
package com.bitwiseglobal.graph.filter;
