//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.19 at 05:36:19 PM IST 
//


package com.bitwiseglobal.graph.inputtypes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bitwiseglobal.graph.inputtypes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bitwiseglobal.graph.inputtypes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TextFileDelimited }
     * 
     */
    public TextFileDelimited createTextFileDelimited() {
        return new TextFileDelimited();
    }

    /**
     * Create an instance of {@link TextFileFixedWidth }
     * 
     */
    public TextFileFixedWidth createTextFileFixedWidth() {
        return new TextFileFixedWidth();
    }

    /**
     * Create an instance of {@link ParquetFile }
     * 
     */
    public ParquetFile createParquetFile() {
        return new ParquetFile();
    }

    /**
     * Create an instance of {@link TextFileMixedScheme }
     * 
     */
    public TextFileMixedScheme createTextFileMixedScheme() {
        return new TextFileMixedScheme();
    }

    /**
     * Create an instance of {@link GenerateRecord }
     * 
     */
    public GenerateRecord createGenerateRecord() {
        return new GenerateRecord();
    }

    /**
     * Create an instance of {@link Subgraph }
     * 
     */
    public Subgraph createSubgraph() {
        return new Subgraph();
    }

    /**
     * Create an instance of {@link ParquetHiveFile }
     * 
     */
    public ParquetHiveFile createParquetHiveFile() {
        return new ParquetHiveFile();
    }

    /**
     * Create an instance of {@link TextFileDelimited.Path }
     * 
     */
    public TextFileDelimited.Path createTextFileDelimitedPath() {
        return new TextFileDelimited.Path();
    }

    /**
     * Create an instance of {@link TextFileDelimited.Delimiter }
     * 
     */
    public TextFileDelimited.Delimiter createTextFileDelimitedDelimiter() {
        return new TextFileDelimited.Delimiter();
    }

    /**
     * Create an instance of {@link TextFileDelimited.Charset }
     * 
     */
    public TextFileDelimited.Charset createTextFileDelimitedCharset() {
        return new TextFileDelimited.Charset();
    }

    /**
     * Create an instance of {@link TextFileDelimited.Quote }
     * 
     */
    public TextFileDelimited.Quote createTextFileDelimitedQuote() {
        return new TextFileDelimited.Quote();
    }

    /**
     * Create an instance of {@link TextFileFixedWidth.Path }
     * 
     */
    public TextFileFixedWidth.Path createTextFileFixedWidthPath() {
        return new TextFileFixedWidth.Path();
    }

    /**
     * Create an instance of {@link TextFileFixedWidth.Charset }
     * 
     */
    public TextFileFixedWidth.Charset createTextFileFixedWidthCharset() {
        return new TextFileFixedWidth.Charset();
    }

    /**
     * Create an instance of {@link ParquetFile.Path }
     * 
     */
    public ParquetFile.Path createParquetFilePath() {
        return new ParquetFile.Path();
    }

    /**
     * Create an instance of {@link TextFileMixedScheme.Path }
     * 
     */
    public TextFileMixedScheme.Path createTextFileMixedSchemePath() {
        return new TextFileMixedScheme.Path();
    }

    /**
     * Create an instance of {@link TextFileMixedScheme.Charset }
     * 
     */
    public TextFileMixedScheme.Charset createTextFileMixedSchemeCharset() {
        return new TextFileMixedScheme.Charset();
    }

    /**
     * Create an instance of {@link GenerateRecord.RecordCount }
     * 
     */
    public GenerateRecord.RecordCount createGenerateRecordRecordCount() {
        return new GenerateRecord.RecordCount();
    }

    /**
     * Create an instance of {@link Subgraph.Path }
     * 
     */
    public Subgraph.Path createSubgraphPath() {
        return new Subgraph.Path();
    }

}
