//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:12:07 PM IST 
//


package com.bitwiseglobal.graph.inputtypes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bitwiseglobal.graph.inputtypes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bitwiseglobal.graph.inputtypes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FileFixedWidth }
     * 
     */
    public FileFixedWidth createFileFixedWidth() {
        return new FileFixedWidth();
    }

    /**
     * Create an instance of {@link InputFileMixedSchemeText }
     * 
     */
    public InputFileMixedSchemeText createInputFileMixedSchemeText() {
        return new InputFileMixedSchemeText();
    }

    /**
     * Create an instance of {@link FileDelimited }
     * 
     */
    public FileDelimited createFileDelimited() {
        return new FileDelimited();
    }

    /**
     * Create an instance of {@link GenerateRecord }
     * 
     */
    public GenerateRecord createGenerateRecord() {
        return new GenerateRecord();
    }

    /**
     * Create an instance of {@link InputFileParquet }
     * 
     */
    public InputFileParquet createInputFileParquet() {
        return new InputFileParquet();
    }

    /**
     * Create an instance of {@link InputHiveParquet }
     * 
     */
    public InputHiveParquet createInputHiveParquet() {
        return new InputHiveParquet();
    }

    /**
     * Create an instance of {@link FileFixedWidth.Path }
     * 
     */
    public FileFixedWidth.Path createFileFixedWidthPath() {
        return new FileFixedWidth.Path();
    }

    /**
     * Create an instance of {@link FileFixedWidth.Charset }
     * 
     */
    public FileFixedWidth.Charset createFileFixedWidthCharset() {
        return new FileFixedWidth.Charset();
    }

    /**
     * Create an instance of {@link InputFileMixedSchemeText.Path }
     * 
     */
    public InputFileMixedSchemeText.Path createInputFileMixedSchemeTextPath() {
        return new InputFileMixedSchemeText.Path();
    }

    /**
     * Create an instance of {@link InputFileMixedSchemeText.Charset }
     * 
     */
    public InputFileMixedSchemeText.Charset createInputFileMixedSchemeTextCharset() {
        return new InputFileMixedSchemeText.Charset();
    }

    /**
     * Create an instance of {@link FileDelimited.Path }
     * 
     */
    public FileDelimited.Path createFileDelimitedPath() {
        return new FileDelimited.Path();
    }

    /**
     * Create an instance of {@link FileDelimited.Delimiter }
     * 
     */
    public FileDelimited.Delimiter createFileDelimitedDelimiter() {
        return new FileDelimited.Delimiter();
    }

    /**
     * Create an instance of {@link FileDelimited.Charset }
     * 
     */
    public FileDelimited.Charset createFileDelimitedCharset() {
        return new FileDelimited.Charset();
    }

    /**
     * Create an instance of {@link FileDelimited.Quote }
     * 
     */
    public FileDelimited.Quote createFileDelimitedQuote() {
        return new FileDelimited.Quote();
    }

    /**
     * Create an instance of {@link GenerateRecord.RecordCount }
     * 
     */
    public GenerateRecord.RecordCount createGenerateRecordRecordCount() {
        return new GenerateRecord.RecordCount();
    }

    /**
     * Create an instance of {@link InputFileParquet.Path }
     * 
     */
    public InputFileParquet.Path createInputFileParquetPath() {
        return new InputFileParquet.Path();
    }

}
