//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.17 at 04:03:17 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bitwiseglobal.com/graph/inputtypes")
package com.bitwiseglobal.graph.inputtypes;
