//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.19 at 05:36:19 PM IST 
//


package com.bitwiseglobal.graph.ofmixedscheme;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bitwiseglobal.graph.ofmixedscheme package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bitwiseglobal.graph.ofmixedscheme
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TypeMixedBase }
     * 
     */
    public TypeMixedBase createTypeMixedBase() {
        return new TypeMixedBase();
    }

    /**
     * Create an instance of {@link TypeOutputMixedInSocket }
     * 
     */
    public TypeOutputMixedInSocket createTypeOutputMixedInSocket() {
        return new TypeOutputMixedInSocket();
    }

    /**
     * Create an instance of {@link TypeMixedRecord }
     * 
     */
    public TypeMixedRecord createTypeMixedRecord() {
        return new TypeMixedRecord();
    }

    /**
     * Create an instance of {@link TypeMixedField }
     * 
     */
    public TypeMixedField createTypeMixedField() {
        return new TypeMixedField();
    }

}
