//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.28 at 02:50:05 PM IST 
//


package com.bitwiseglobal.graph.main;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.bitwiseglobal.graph.commontypes.TypeBaseComponent;
import com.bitwiseglobal.graph.commontypes.TypeCommandComponent;
import com.bitwiseglobal.graph.commontypes.TypeInputComponent;
import com.bitwiseglobal.graph.commontypes.TypeOutputComponent;
import com.bitwiseglobal.graph.commontypes.TypeStraightPullComponent;
import com.bitwiseglobal.graph.commontypes.TypeTransformComponent;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="input" type="{http://www.bitwiseglobal.com/graph/commontypes}type-input-component"/>
 *         &lt;element name="output" type="{http://www.bitwiseglobal.com/graph/commontypes}type-output-component"/>
 *         &lt;element name="straight-pull" type="{http://www.bitwiseglobal.com/graph/commontypes}type-straight-pull-component"/>
 *         &lt;element name="transform" type="{http://www.bitwiseglobal.com/graph/commontypes}type-transform-component"/>
 *         &lt;element name="command" type="{http://www.bitwiseglobal.com/graph/commontypes}type-command-component"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputOrOutputOrStraightPull"
})
@XmlRootElement(name = "graph")
public class Graph {

    @XmlElements({
        @XmlElement(name = "input", type = TypeInputComponent.class),
        @XmlElement(name = "output", type = TypeOutputComponent.class),
        @XmlElement(name = "straight-pull", type = TypeStraightPullComponent.class),
        @XmlElement(name = "transform", type = TypeTransformComponent.class),
        @XmlElement(name = "command", type = TypeCommandComponent.class)
    })
    protected List<TypeBaseComponent> inputOrOutputOrStraightPull;

    /**
     * Gets the value of the inputOrOutputOrStraightPull property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputOrOutputOrStraightPull property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputOrOutputOrStraightPull().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeInputComponent }
     * {@link TypeOutputComponent }
     * {@link TypeStraightPullComponent }
     * {@link TypeTransformComponent }
     * {@link TypeCommandComponent }
     * 
     * 
     */
    public List<TypeBaseComponent> getInputOrOutputOrStraightPull() {
        if (inputOrOutputOrStraightPull == null) {
            inputOrOutputOrStraightPull = new ArrayList<TypeBaseComponent>();
        }
        return this.inputOrOutputOrStraightPull;
    }

}
