//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:12:07 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bitwiseglobal.com/graph/ottrash")
package com.bitwiseglobal.graph.ottrash;
