//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.16 at 05:21:26 PM IST 
//


package com.bitwiseglobal.graph.commontypes;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import com.bitwiseglobal.graph.filter.TypeFilterOperation;
import com.bitwiseglobal.graph.reformat.TypeReformatOperation;


/**
 * <p>Java class for type-transform-operation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="type-transform-operation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inputFields" type="{http://www.bitwiseglobal.com/graph/commontypes}type-operation-input-fields" minOccurs="0"/>
 *         &lt;element name="outputFields" type="{http://www.bitwiseglobal.com/graph/commontypes}type-operation-output-fields" minOccurs="0"/>
 *         &lt;element name="properties" type="{http://www.bitwiseglobal.com/graph/commontypes}type-properties" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "type-transform-operation", propOrder = {
    "inputFields",
    "outputFields",
    "properties"
})
@XmlSeeAlso({
    TypeReformatOperation.class,
    com.bitwiseglobal.graph.aggregate.TypeOperation.class,
    TypeFilterOperation.class,
    com.bitwiseglobal.graph.uniquesequence.TypeOperation.class,
    com.bitwiseglobal.graph.scan.TypeOperation.class,
    com.bitwiseglobal.graph.normalize.TypeOperation.class
})
public class TypeTransformOperation {

    protected TypeOperationInputFields inputFields;
    protected TypeOperationOutputFields outputFields;
    protected TypeProperties properties;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the inputFields property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOperationInputFields }
     *     
     */
    public TypeOperationInputFields getInputFields() {
        return inputFields;
    }

    /**
     * Sets the value of the inputFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOperationInputFields }
     *     
     */
    public void setInputFields(TypeOperationInputFields value) {
        this.inputFields = value;
    }

    /**
     * Gets the value of the outputFields property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOperationOutputFields }
     *     
     */
    public TypeOperationOutputFields getOutputFields() {
        return outputFields;
    }

    /**
     * Sets the value of the outputFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOperationOutputFields }
     *     
     */
    public void setOutputFields(TypeOperationOutputFields value) {
        this.outputFields = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link TypeProperties }
     *     
     */
    public TypeProperties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeProperties }
     *     
     */
    public void setProperties(TypeProperties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
