//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.04 at 12:53:22 PM IST 
//


package com.bitwise.app.common.component.policyconfig;

import javax.xml.bind.annotation.XmlRegistry;

import com.bitwise.app.common.component.config.Policy;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bitwise.app.common.component.policyconfig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bitwise.app.common.component.policyconfig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PolicyConfig }
     * 
     */
    public PolicyConfig createPolicyConfig() {
        return new PolicyConfig();
    }

    /**
     * Create an instance of {@link MasterPolicies }
     * 
     */
    public MasterPolicies createMasterPolicies() {
        return new MasterPolicies();
    }

    /**
     * Create an instance of {@link CategoryPolicies }
     * 
     */
    public CategoryPolicies createCategoryPolicies() {
        return new CategoryPolicies();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

}
