//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 08:37:05 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bitwise.com/ComponentConfig", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bitwise.app.common.component.config;
